runtime: go
api_version: go1
service: backend

handlers:
- url: /.*
  script: _go_app

env_variables:
  ALLOWED_ORIGIN: "https://bboy-jam-dev-218006.appspot.com,https://bboy-jam-prod.appspot.com,https://www.bboybracket.com"
